# Generated by Django 4.1 on 2022-08-12 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tnved',
            name='code',
            field=models.CharField(max_length=12, verbose_name='Номер группы'),
        ),
        migrations.AlterField(
            model_name='tnved',
            name='subposition',
            field=models.TextField(verbose_name='Подсубпозиция'),
        ),
    ]
