# Generated by Django 4.1 on 2022-08-13 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_tnved_code_alter_tnved_subposition'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gtdmain',
            name='gtdId',
            field=models.CharField(max_length=23, unique=True, verbose_name='Номер гтд'),
        ),
        migrations.AlterUniqueTogether(
            name='exporter',
            unique_together={('name', 'postal_code')},
        ),
        migrations.AlterUniqueTogether(
            name='importer',
            unique_together={('name', 'inn', 'ogrn')},
        ),
    ]
