# Generated by Django 4.1 on 2022-08-13 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_importer_unique_together_alter_exporter_name_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='exporter',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='exporter',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Название компании'),
        ),
        migrations.AlterUniqueTogether(
            name='exporter',
            unique_together={('name', 'postal_code', 'city', 'street_house')},
        ),
    ]
