# Generated by Django 4.1 on 2022-08-14 18:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_rename_document_name_document_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MeasureQualifier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('digital_code', models.CharField(max_length=4, unique=True, verbose_name='Код')),
                ('name', models.CharField(max_length=50, verbose_name='Наименование')),
                ('russian_symbol', models.CharField(blank=True, max_length=10, null=True, verbose_name='Русское условное обозначение')),
                ('russian_code', models.CharField(blank=True, max_length=10, null=True, verbose_name='Русское кодовое обозначение')),
                ('english_symbol', models.CharField(blank=True, max_length=10, null=True, verbose_name='Международное условное обозначение')),
                ('english_code', models.CharField(blank=True, max_length=10, null=True, verbose_name='Международное кодовое обозначение')),
            ],
            options={
                'verbose_name': 'Единица измерения',
                'verbose_name_plural': 'Единицы измерения',
            },
        ),
        migrations.AlterModelOptions(
            name='document',
            options={'verbose_name': 'Документ', 'verbose_name_plural': 'Документы'},
        ),
        migrations.AlterModelOptions(
            name='goodsmark',
            options={'verbose_name': 'Торговая марка', 'verbose_name_plural': 'Торговые марки'},
        ),
        migrations.AlterModelOptions(
            name='gtddocument',
            options={'verbose_name': 'Документ в ГТД', 'verbose_name_plural': 'Документы в ГТД'},
        ),
        migrations.AlterModelOptions(
            name='manufacturer',
            options={'verbose_name': 'Производитель', 'verbose_name_plural': 'Производители'},
        ),
        migrations.AlterModelOptions(
            name='trademark',
            options={'verbose_name': 'Товарный знак', 'verbose_name_plural': 'Товарные знаки'},
        ),
        migrations.AlterModelOptions(
            name='uploadgtd',
            options={'ordering': ['uploaded_at'], 'verbose_name': 'Загруженная ГТД', 'verbose_name_plural': 'Загруженные ГТД'},
        ),
        migrations.AlterModelOptions(
            name='userrole',
            options={'verbose_name': 'Роль пользователя', 'verbose_name_plural': 'Роли пользователей'},
        ),
        migrations.AlterField(
            model_name='good',
            name='name',
            field=models.TextField(verbose_name='Товар'),
        ),
        migrations.AlterField(
            model_name='gtdgood',
            name='quantity',
            field=models.FloatField(verbose_name='Количество'),
        ),
        migrations.AddField(
            model_name='gtdgood',
            name='qualifier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='main.measurequalifier', verbose_name='id единицы измерения'),
        ),
    ]
