# Generated by Django 4.1 on 2022-08-14 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_alter_measurequalifier_english_symbol'),
    ]

    operations = [
        migrations.AlterField(
            model_name='measurequalifier',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Наименование'),
        ),
    ]
