# Generated by Django 4.1 on 2022-08-14 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_alter_measurequalifier_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='measurequalifier',
            name='english_code',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Международное кодовое обозначение'),
        ),
        migrations.AlterField(
            model_name='measurequalifier',
            name='russian_code',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Русское кодовое обозначение'),
        ),
        migrations.AlterField(
            model_name='measurequalifier',
            name='russian_symbol',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Русское условное обозначение'),
        ),
    ]
