# Generated by Django 4.1 on 2022-08-15 07:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_alter_measurequalifier_english_symbol_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='gtdgood',
            unique_together={('gtd', 'group', 'good_num')},
        ),
    ]
