# Generated by Django 4.1 on 2022-08-16 05:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_documenttype_alter_gtddocument_unique_together_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='good',
            old_name='brand',
            new_name='goodsmark',
        ),
        migrations.RenameField(
            model_name='goodsmark',
            old_name='brand',
            new_name='goodsmark',
        ),
        migrations.RemoveField(
            model_name='gtddocument',
            name='present_code',
        ),
        migrations.DeleteModel(
            name='PresentCode',
        ),
    ]
