# Generated by Django 4.1 on 2022-08-16 10:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_alter_gtdmain_gtdid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='good',
            name='goodsmark',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='main.goodsmark', verbose_name='id торговой марки'),
        ),
        migrations.AlterField(
            model_name='good',
            name='trademark',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='main.trademark', verbose_name='id товарного знака'),
        ),
    ]
