# Generated by Django 4.1 on 2022-08-16 10:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0020_alter_good_goodsmark_alter_good_trademark'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gtdgood',
            name='manufacturer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='main.manufacturer', verbose_name='id производителя'),
        ),
    ]
