# Generated by Django 4.1 on 2022-08-16 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0021_alter_gtdgood_manufacturer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='begin_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата начала действия'),
        ),
        migrations.AlterField(
            model_name='document',
            name='date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата'),
        ),
        migrations.AlterField(
            model_name='document',
            name='expire_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата окончания действия'),
        ),
    ]
