# Generated by Django 4.1 on 2022-08-16 12:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0022_alter_document_begin_date_alter_document_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gtdgood',
            name='good',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='main.good', verbose_name='id товара'),
        ),
    ]
