# Generated by Django 4.1 on 2022-08-16 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0023_alter_gtdgood_good'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gtdgood',
            name='quantity',
            field=models.FloatField(blank=True, null=True, verbose_name='Количество'),
        ),
    ]
