# Generated by Django 4.1 on 2022-08-16 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0025_alter_document_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='good',
            name='marking',
            field=models.CharField(max_length=50, verbose_name='Артикул'),
        ),
    ]
