# Generated by Django 4.1 on 2022-08-16 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0026_alter_good_marking'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tnved',
            name='code',
            field=models.CharField(max_length=18, verbose_name='Номер группы'),
        ),
    ]
