# Generated by Django 4.1 on 2022-08-16 19:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0027_alter_tnved_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gtdgroup',
            name='tn_ved',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='main.tnved', verbose_name='id кода товарной группы ТН ВЭД'),
        ),
    ]
