# Generated by Django 4.1 on 2022-08-17 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0028_alter_gtdgroup_tn_ved'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tnved',
            name='subposition',
            field=models.TextField(blank=True, null=True, verbose_name='Подсубпозиция'),
        ),
    ]
