# Generated by Django 4.1 on 2022-08-17 18:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0029_alter_tnved_subposition'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customshouse',
            options={'verbose_name': 'Таможенный отдел', 'verbose_name_plural': 'Таможенные отделы'},
        ),
        migrations.AlterUniqueTogether(
            name='gtdmain',
            unique_together={('gtdId', 'customs_house', 'date', 'order_num')},
        ),
    ]
