# Generated by Django 4.1 on 2022-08-17 19:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0030_alter_customshouse_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='importer',
            name='country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='main.country', verbose_name='id страны'),
        ),
        migrations.AlterField(
            model_name='importer',
            name='kpp',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='КПП'),
        ),
    ]
