# Generated by Django 4.1 on 2022-08-18 08:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0031_alter_importer_country_alter_importer_kpp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gtdmain',
            name='currency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='currencies', to='main.currency', verbose_name='id валюты'),
        ),
        migrations.AlterField(
            model_name='gtdmain',
            name='customs_house',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='customs_houses', to='main.customshouse', verbose_name='id таможенного отделения'),
        ),
        migrations.AlterField(
            model_name='gtdmain',
            name='deal_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='deal_types', to='main.dealtype', verbose_name='id характера сделки'),
        ),
        migrations.AlterField(
            model_name='gtdmain',
            name='exporter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='exporters', to='main.exporter', verbose_name='id Экспортера'),
        ),
        migrations.AlterField(
            model_name='gtdmain',
            name='gtd_file',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='gtd_files', to='main.uploadgtd', verbose_name='id xml-документа гтд'),
        ),
        migrations.AlterField(
            model_name='gtdmain',
            name='importer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='importers', to='main.importer', verbose_name='id импортера'),
        ),
        migrations.AlterField(
            model_name='gtdmain',
            name='trading_country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='trading_countries', to='main.country', verbose_name='id торгующей страны'),
        ),
        migrations.AlterField(
            model_name='userrole',
            name='role',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='roles', to='main.role', verbose_name='id роли'),
        ),
        migrations.AlterField(
            model_name='userrole',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='users', to=settings.AUTH_USER_MODEL, verbose_name='id пользователя'),
        ),
    ]
