# Generated by Django 4.1 on 2022-08-21 08:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0032_alter_gtdmain_currency_alter_gtdmain_customs_house_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='uploadgtd',
            name='document',
        ),
        migrations.CreateModel(
            name='UploadGtdFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document', models.FileField(upload_to='gtd/')),
                ('uploaded_gtd', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.uploadgtd', verbose_name='id партии загруженных ГТД')),
            ],
            options={
                'verbose_name': 'Загруженный файл ГТД',
                'verbose_name_plural': 'Загруженные файлы ГТД',
            },
        ),
    ]
