# Generated by Django 4.1 on 2022-08-21 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0033_remove_uploadgtd_document_uploadgtdfile'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadgtd',
            name='files_num',
            field=models.IntegerField(blank=True, null=True, verbose_name='Количество прикрепленных файлов'),
        ),
    ]
