# Generated by Django 4.1 on 2022-08-21 12:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0034_uploadgtd_files_num'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadgtdfile',
            name='uploaded_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='gtdmain',
            name='gtd_file',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='gtd_files', to='main.uploadgtdfile', verbose_name='id xml-документа гтд'),
        ),
    ]
