# Generated by Django 4.1 on 2022-08-21 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0035_uploadgtdfile_uploaded_at_alter_gtdmain_gtd_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manufacturer',
            name='manufacturer',
            field=models.CharField(max_length=255, verbose_name='Производитель'),
        ),
    ]
