# Generated by Django 4.1 on 2022-08-22 07:41

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0036_alter_manufacturer_manufacturer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='role',
            old_name='role_name',
            new_name='name',
        ),
        migrations.AddField(
            model_name='role',
            name='roles',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='reguser',
            name='email',
            field=models.EmailField(max_length=254, unique=True, verbose_name='Электронная почта'),
        ),
        migrations.DeleteModel(
            name='UserRole',
        ),
    ]
