# Generated by Django 4.1 on 2022-08-22 07:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0037_rename_role_name_role_name_role_roles_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='role',
            old_name='roles',
            new_name='users',
        ),
    ]
