# Generated by Django 4.1 on 2022-08-22 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0038_rename_roles_role_users'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='role',
            name='users',
        ),
        migrations.AddField(
            model_name='reguser',
            name='roles',
            field=models.ManyToManyField(to='main.role', verbose_name='Роли пользователя'),
        ),
    ]
