# Generated by Django 4.1 on 2022-08-22 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0040_alter_role_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='role',
            name='name',
            field=models.CharField(max_length=60, unique=True, verbose_name='Роль'),
        ),
    ]
