# Generated by Django 4.1 on 2022-08-23 13:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0042_remove_reguser_roles_gtdgood_slug_gtdgroup_slug_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gtdgood',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='gtdgroup',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='gtdmain',
            name='slug',
        ),
    ]
