# Generated by Django 4.1 on 2022-08-24 05:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0043_remove_gtdgood_slug_remove_gtdgroup_slug_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reguser',
            name='is_activated',
        ),
    ]
