# Generated by Django 4.1 on 2022-08-26 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0047_alter_document_doc_type_alter_gtddocument_document_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='gtdgroup',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='gtdgroup',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='country',
            name='english_name',
            field=models.CharField(max_length=150, verbose_name='Название страны на английском'),
        ),
        migrations.AlterField(
            model_name='country',
            name='russian_name',
            field=models.CharField(max_length=150, verbose_name='Название страны на русском'),
        ),
        migrations.AlterField(
            model_name='documenttype',
            name='code',
            field=models.CharField(max_length=8, verbose_name='Код типа документа'),
        ),
    ]
