# Generated by Django 4.1 on 2022-08-31 12:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0051_rename_last_edited_gtdmain_last_edited_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gtddocument',
            name='gtd',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='main.gtdmain', verbose_name='id ГТД'),
        ),
        migrations.AlterField(
            model_name='gtdgood',
            name='gtd',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='main.gtdmain', verbose_name='id ГТД'),
        ),
        migrations.AlterField(
            model_name='gtdgroup',
            name='gtd',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='main.gtdmain', verbose_name='id ГТД'),
        ),
    ]
