# Generated by Django 4.1 on 2022-09-05 09:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0054_alter_reguser_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reguser',
            name='done_registration',
        ),
    ]
