# Generated by Django 4.1 on 2022-09-11 17:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0056_alter_gtdmain_gtdid'),
    ]

    operations = [
        migrations.AddField(
            model_name='gtdgood',
            name='last_edited_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь, последний внесший изменения'),
        ),
    ]
