# Generated by Django 4.1 on 2022-09-11 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0057_gtdgood_last_edited_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='good',
            name='marking',
            field=models.CharField(max_length=50, verbose_name='Артикул'),
        ),
    ]
