# Generated by Django 4.1 on 2022-09-19 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0060_gtdgroup_last_edited_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='good',
            name='marking',
            field=models.CharField(default='MSAG1-12HRN1-I', max_length=50, verbose_name='Артикул'),
            preserve_default=False,
        ),
    ]
