# Generated by Django 4.1 on 2022-09-19 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0061_alter_good_marking'),
    ]

    operations = [
        migrations.AddField(
            model_name='tnved',
            name='has_environmental_fee',
            field=models.BooleanField(blank=True, null=True, verbose_name='Облагается ли экологическим сбором?'),
        ),
    ]
