# Generated by Django 4.1 on 2022-09-19 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0062_tnved_has_environmental_fee'),
    ]

    operations = [
        migrations.AddField(
            model_name='tnved',
            name='recycling_standart',
            field=models.FloatField(blank=True, null=True, verbose_name='Норма утилизации'),
        ),
    ]
