# Generated by Django 4.1 on 2022-09-23 05:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0063_tnved_recycling_standart'),
    ]

    operations = [
        migrations.AddField(
            model_name='tnved',
            name='collection_rate',
            field=models.FloatField(blank=True, null=True, verbose_name='Ставка сбора'),
        ),
        migrations.AlterField(
            model_name='document',
            name='doc_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='main.documenttype', verbose_name='Id типа документа'),
        ),
        migrations.AlterField(
            model_name='exporter',
            name='country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='main.country', verbose_name='id страны'),
        ),
        migrations.AlterField(
            model_name='good',
            name='goodsmark',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='main.goodsmark', verbose_name='id торговой марки'),
        ),
        migrations.AlterField(
            model_name='good',
            name='trademark',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='main.trademark', verbose_name='id товарного знака'),
        ),
        migrations.AlterField(
            model_name='gtdgood',
            name='good',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='main.good', verbose_name='id товара'),
        ),
        migrations.AlterField(
            model_name='gtdgood',
            name='last_edited_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь, последний внесший изменения'),
        ),
        migrations.AlterField(
            model_name='gtdgood',
            name='manufacturer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='main.manufacturer', verbose_name='id производителя'),
        ),
        migrations.AlterField(
            model_name='gtdgood',
            name='qualifier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='main.measurequalifier', verbose_name='id единицы измерения'),
        ),
        migrations.AlterField(
            model_name='gtdgroup',
            name='country',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='main.country', verbose_name='id страны происхождения'),
        ),
        migrations.AlterField(
            model_name='gtdgroup',
            name='last_edited_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь, последний вносивший изменения'),
        ),
        migrations.AlterField(
            model_name='gtdgroup',
            name='prev_procedure',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='main.procedure', verbose_name='id предыдущей таможенной процедуры'),
        ),
        migrations.AlterField(
            model_name='gtdgroup',
            name='procedure',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='main.procedure', verbose_name='id завляемой таможенной процедуры'),
        ),
        migrations.AlterField(
            model_name='gtdgroup',
            name='tn_ved',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='main.tnved', verbose_name='id кода товарной группы ТН ВЭД'),
        ),
        migrations.AlterField(
            model_name='gtdmain',
            name='currency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='main.currency', verbose_name='id валюты'),
        ),
        migrations.AlterField(
            model_name='gtdmain',
            name='customs_house',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='main.customshouse', verbose_name='id таможенного отделения'),
        ),
        migrations.AlterField(
            model_name='gtdmain',
            name='deal_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='main.dealtype', verbose_name='id характера сделки'),
        ),
        migrations.AlterField(
            model_name='gtdmain',
            name='exporter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='main.exporter', verbose_name='id Экспортера'),
        ),
        migrations.AlterField(
            model_name='gtdmain',
            name='gtd_file',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='main.uploadgtdfile', verbose_name='id xml-документа гтд'),
        ),
        migrations.AlterField(
            model_name='gtdmain',
            name='importer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='main.importer', verbose_name='id импортера'),
        ),
        migrations.AlterField(
            model_name='gtdmain',
            name='last_edited_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь, последний внесший изменения'),
        ),
        migrations.AlterField(
            model_name='gtdmain',
            name='trading_country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='main.country', verbose_name='id торгующей страны'),
        ),
        migrations.AlterField(
            model_name='importer',
            name='country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='main.country', verbose_name='id страны'),
        ),
        migrations.AlterField(
            model_name='uploadgtd',
            name='who_uploaded',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь, загрузивший файл(ы)'),
        ),
        migrations.AlterField(
            model_name='uploadgtdfile',
            name='uploaded_gtd',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.uploadgtd', verbose_name='id партии загруженных ГТД'),
        ),
    ]
