# Generated by Django 4.1 on 2022-10-09 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0064_tnved_collection_rate_alter_document_doc_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tnved',
            name='collection_rate',
            field=models.FloatField(blank=True, max_length=255, null=True, verbose_name='Ставка сбора'),
        ),
        migrations.AlterField(
            model_name='tnved',
            name='has_environmental_fee',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Облагается ли экологическим сбором?'),
        ),
        migrations.AlterField(
            model_name='tnved',
            name='recycling_standart',
            field=models.FloatField(blank=True, max_length=255, null=True, verbose_name='Норма утилизации'),
        ),
    ]
