# Generated by Django 4.1 on 2022-10-09 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0066_alter_tnved_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tnved',
            name='code',
            field=models.CharField(max_length=18, verbose_name='Номер группы'),
        ),
    ]
