# Generated by Django 4.1 on 2022-10-24 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0067_alter_tnved_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='gtdmain',
            name='exported_to_erp',
            field=models.BooleanField(default=False, verbose_name='Был выполнен экспорт в ERP?'),
        ),
        migrations.AddField(
            model_name='gtdmain',
            name='exported_to_wms',
            field=models.BooleanField(default=False, verbose_name='Был выполнен экспорт в WMS?'),
        ),
    ]
