# Generated by Django 4.1 on 2022-10-25 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0069_alter_uploadgtdfile_uploaded_gtd_wmsexport'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobTitle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Должность')),
            ],
        ),
        migrations.AddField(
            model_name='reguser',
            name='role',
            field=models.ManyToManyField(blank=True, null=True, related_name='+', to='main.jobtitle', verbose_name='Должность'),
        ),
    ]
