# Generated by Django 4.1 on 2022-10-25 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0070_jobtitle_reguser_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reguser',
            name='role',
        ),
        migrations.AddField(
            model_name='reguser',
            name='roles',
            field=models.ManyToManyField(blank=True, null=True, related_name='+', to='main.jobtitle', verbose_name='Должность'),
        ),
    ]
