# Generated by Django 4.1 on 2022-10-25 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0071_remove_reguser_role_reguser_roles'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reguser',
            name='roles',
            field=models.ManyToManyField(blank=True, related_name='+', to='main.jobtitle', verbose_name='Должность'),
        ),
    ]
