# Generated by Django 4.1 on 2022-10-25 09:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0072_alter_reguser_roles'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reguser',
            name='roles',
        ),
        migrations.DeleteModel(
            name='JobTitle',
        ),
    ]
