# Generated by Django 4.1 on 2022-10-29 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0075_remove_reguser_roles_delete_jobtitle'),
    ]

    operations = [
        migrations.AddField(
            model_name='reguser',
            name='patronymic',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Отчество'),
        ),
    ]
