# Generated by Django 4.1 on 2022-10-30 08:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0076_reguser_patronymic'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gtdgroup',
            name='description',
        ),
    ]
