# Generated by Django 4.1 on 2022-10-30 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0078_alter_gtdgroup_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='good',
            name='marking',
            field=models.CharField(max_length=50, unique=True, verbose_name='Артикул'),
        ),
    ]
