# Generated by Django 4.1 on 2022-10-31 08:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0079_alter_good_marking'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='importer',
            unique_together={('name', 'postal_code')},
        ),
    ]
