# Generated by Django 4.1 on 2022-11-02 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0080_alter_importer_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='reguser',
            name='is_activated',
            field=models.BooleanField(default=False, verbose_name='Завершил регистрацию?'),
        ),
    ]
