# Generated by Django 4.1 on 2022-11-03 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0081_reguser_is_activated'),
    ]

    operations = [
        migrations.CreateModel(
            name='Handbook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('is_actual_table', models.BooleanField(default=False, verbose_name='Актуальная таблица')),
            ],
        ),
    ]
