# Generated by Django 4.1 on 2022-11-05 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0083_alter_gtdgood_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='handbook',
            name='name',
            field=models.CharField(max_length=255, unique=True, verbose_name='Название'),
        ),
    ]
