# Generated by Django 4.1 on 2022-11-05 18:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0084_alter_handbook_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='wmsexport',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь, выполнивший экспорт'),
        ),
        migrations.AlterField(
            model_name='documenttype',
            name='name',
            field=models.TextField(verbose_name='Тип документа'),
        ),
        migrations.AlterField(
            model_name='exporter',
            name='country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='main.country', verbose_name='Страна'),
        ),
        migrations.AlterField(
            model_name='good',
            name='goodsmark',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='main.goodsmark', verbose_name='Торговая марка'),
        ),
        migrations.AlterField(
            model_name='good',
            name='trademark',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='main.trademark', verbose_name='Товарный знак'),
        ),
        migrations.AlterField(
            model_name='importer',
            name='country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='main.country', verbose_name='Страна'),
        ),
        migrations.CreateModel(
            name='ErpExport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(default='', verbose_name='Комментарий')),
                ('filename', models.CharField(max_length=255, verbose_name='Имя файла')),
                ('datetime', models.DateTimeField(auto_now_add=True)),
                ('gtd', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='main.gtdmain', verbose_name='id ГТД')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь, выполнивший экспорт')),
            ],
        ),
    ]
