# Generated by Django 4.1 on 2022-11-06 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0086_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='reguser',
            name='roles',
            field=models.ManyToManyField(blank=True, null=True, to='main.role', verbose_name='Роли'),
        ),
    ]
