# Generated by Django 4.1 on 2022-11-06 10:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0087_reguser_roles'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reguser',
            name='roles',
        ),
        migrations.DeleteModel(
            name='Role',
        ),
    ]
